language: php

php:
    - "7.4"

before_install:
  - composer install
  - composer self-update

env:
    global:
        - XDEBUG_MODE=coverage

sudo: false

git:
    submodules: false


before_script:
    - make install check

script:
    - make test
